app = 'sanya-chat-bot'
primary_region = 'ams'
kill_signal = 'SIGINT'
kill_timeout = '10'

[build]

[env]
  BOT_MODE = 'polling'
  AIMLAPI_URL = 'https://api.aimlapi.com/v1/chat/completions'
  AI_MODEL = 'openai/gpt-4.1-2025-04-14'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
